apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: webapp
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      version: blue
  template:
    metadata:
      labels:
        app: webapp
        version: blue
    spec:
      containers:
      - name: webapp
        image: us-central1-docker.pkg.dev/rock-atlas-451711-a2/blue-green-repo/blue-app:v1
        ports:
        - containerPort: 80
