name: Deploy Blue to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: rock-atlas-451711-a2
  GKE_CLUSTER: blue-green-cluster
  GKE_ZONE: us-central1-a
  IMAGE: blue-app
  IMAGE_TAG: v1
  GAR_ZONE: us-central1
  GAR_REPO: blue-green-repo

jobs:
  build-push-deploy:
    name: Build, Push, and Deploy Blue
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.GAR_ZONE }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build \
            --tag "${{ env.GAR_ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}" \
            .

      - name: Push Docker Image
        run: |
          docker push "${{ env.GAR_ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f blue-deployment.yaml
          kubectl apply -f blue-service.yaml
          kubectl rollout status deployment/blue-deployment
